# Generated by Django 2.2.7 on 2019-11-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='unidades',
            field=models.IntegerField(default=1),
        ),
    ]
