# Generated by Django 2.2.7 on 2019-11-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_pedido_unidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
